export const CART_GET_LOADING = 'CART_GET_LOADING'
export const CART_GET_SUCCESS = 'CART_GET_SUCCESS'
export const CART_GET_ERROR = 'CART_GET_ERROR'

export const CART_POST_LOADING = 'CART_POST_LOADING'
export const CART_POST_SUCCESS = 'CART_POST_SUCCESS'
export const CART_POST_ERROR = 'CART_POST_ERROR'

export const CART_DELETE_LOADING = 'CART_DELETE_LOADING'
export const CART_DELETE_SUCCESS = 'CART_DELETE_SUCCESS'
export const CART_DELETE_ERROR = 'CART_DELETE_ERROR'
