export const REVIEW_GET_LOADING = "REVIEW_GET_LOADING"
export const REVIEW_GET_ERROR = "REVIEW_GET_ERROR"
export const REVIEW_GET_SUCCESS = "REVIEW_GET_SUCCESS"

export const REVIEW_POST_LOADING = "REVIEW_POST_LOADING"
export const REVIEW_POST_ERROR = "REVIEW_POST_ERROR"
export const REVIEW_POST_SUCCESS = "REVIEW_POST_SUCCESS"