export const ORDER_GET_LOADING = 'ORDER_GET_LOADING'
export const ORDER_GET_SUCCESS = 'ORDER_GET_SUCCESS'
export const ORDER_GET_ERROR = 'ORDER_GET_ERROR'

export const ORDER_POST_LOADING = 'ORDER_POST_LOADING'
export const ORDER_POST_SUCCESS = 'ORDER_POST_SUCCESS'
export const ORDER_POST_ERROR = 'ORDER_POST_ERROR'